image: ubuntu:latest

before_script:
 
build:
  stage: build
  tags:
    - docker
  script:
    - pwd
    - apt update
    - apt install -y make
    - apt install -y "gcc"
    - make
    - ./usamba --version
  artifacts:
    paths:
      - usamba
#    expire_in: 1 week
